### ISSUE TITLE
Deploy to Heroku instead of GitHub pages

### ISSUE THREAD

**Issue by anttilip** [JaakkoLipsanen/evento#10]

**Comment by JaakkoLipsanen** [comment]
Might not be possible after all, since right now flai.xyz redirects to evento.flai.xyz

**Comment by anttilip** [comment]
[This](https://github.com/mars/create-react-app-buildpack) might be useful with the transition.

**Comment by JaakkoLipsanen** [comment]
So.. What should we do here? I could probably get evento.flai.xyz to work on Github Pages as well. Some thoughts:

1. On Heroku, there will be "double sleep/wakeup", meaning that since both our front-end and backend are on Heroku, when we visit the website, first the front-end has to wake up (~3-5sec?), then the front-end makes a request to the backend and the backend has to wake up as well (~3-5sec?). Hosting the front-end in Github would avoid the "double sleep", but the backend would still keep sleeping. But it's not that bad, since we can just create a loading page of some kind in the front-end to mask the delay.

2. On Github, we can't use the index.html and instead have to use 404.html, since only url's to the root path (flai.xyz/evento-web at the moment) are redirected to use index.html. 404.html would match all paths. On Heroku, we would create a small (~10 lines of code) Node/Express web-server that redirects all url's to use index.html.

3. On Github, HTTPS is not natively supported on custom domains. [There are some workarounds around that](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/), but dunno. HTTPS is kinda required for authentication.

There are some other options as well, like [Surge](http://surge.sh/) but I don't think that it is any better than Github.
